Repository DohoonHan/D-OH, pull requests merged in 2024-09, with the labels that each got.

#17 14 프로젝트에 thymeleaf 템플릿 엔진 적용
  build.gradle
  src/main/resources/application.yml
  src/main/resources/templates/fragments/footer.html
  src/main/resources/templates/fragments/layout.html
Labels: Front

#20 3 헤더 화면 페이지 구현
  src/main/resources/static/css/fragments/header.css
  src/main/resources/static/img/fragments/logoG.png
  src/main/resources/templates/fragments/footer.html
  src/main/resources/templates/fragments/header.html
Labels: Front

#23 9 공지사항 리스트 페이지 화면 구현
  build.gradle
  src/main/resources/application.yml
  src/main/resources/static/css/notifications/Contest.css
  src/main/resources/static/css/notifications/noticeList.css
  src/main/resources/static/js/notifications/List.css
  src/main/resources/static/js/notifications/noticeList.js
  src/main/resources/templates/fragments/layout.html
  src/main/resources/templates/notifications/List.html
  src/main/resources/templates/notifications/noticeList.html
Labels: Front

#27 공지사항 등록 페이지 화면 구현
  src/main/resources/static/css/notifications/noticeWrite.css
  src/main/resources/static/js/notifications/noticeWrite.js
  src/main/resources/templates/notifications/noticeWrite.html
Labels: Front

#32 이벤트 리스트 페이지 화면 구성
  src/main/resources/static/css/notifications/eventList.css
  src/main/resources/templates/notifications/eventList.html
Labels: Front

#34 이벤트 등록 페이지 화면 구현
  src/main/resources/static/css/notifications/eventWrite.css
  src/main/resources/templates/notifications/eventWrite.html
Labels: Front

#36 이벤트 상세 페이지 파일 분리&수정
  src/main/resources/static/css/notifications/eventView.css
  src/main/resources/static/css/notifications/eventWrite.css
  src/main/resources/static/js/notifications/eventView.js
  src/main/resources/templates/notifications/eventView.html
Labels: Front

#39 404에러 랜덤으로 나오게 완성
  src/main/resources/static/img/fragments/404.gif
  src/main/resources/static/img/fragments/404h.gif
  src/main/resources/static/img/fragments/sa.gif
  src/main/resources/static/img/fragments/ssa.gif
  src/main/resources/templates/error/404.html
Labels: enhancement

#47 37 이벤트 페이지 구현
  src/main/java/com/DOH/DOH/controller/notifications/EventController.java
  src/main/java/com/DOH/DOH/dto/notifications/EventDTO.java
  src/main/java/com/DOH/DOH/mapper/notifications/EventMapper.java
  src/main/java/com/DOH/DOH/service/notifications/EventService.java
  src/main/java/com/DOH/DOH/service/notifications/EventServiceImpl.java
  src/main/resources/mapper/notifications/EventMapper.xml
  src/main/resources/static/css/notifications/eventList.css
  src/main/resources/static/css/notifications/eventView.css
  src/main/resources/static/css/notifications/eventWrite.css
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/notifications/eventList.html
  src/main/resources/templates/notifications/eventView.html
  src/main/resources/templates/notifications/eventWrite.html
Labels: Back

#48 22 공지사항 페이지 구현
  build.gradle
  src/main/java/com/DOH/DOH/controller/notifications/NoticeController.java
  src/main/java/com/DOH/DOH/dto/notifications/NoticeDTO.java
  src/main/java/com/DOH/DOH/mapper/notifications/NoticeMapper.java
  src/main/java/com/DOH/DOH/service/notifications/NoticeService.java
  src/main/java/com/DOH/DOH/service/notifications/NoticeServiceImpl.java
  src/main/resources/mapper/notifications/NoticeMapper.xml
  src/main/resources/static/css/notifications/noticeList.css
  src/main/resources/static/css/notifications/noticeWrite.css
  src/main/resources/static/js/notifications/noticeList.js
  src/main/resources/static/js/notifications/noticeWrite.js
  src/main/resources/templates/fragments/layout.html
  src/main/resources/templates/notifications/noticeList.html
  src/main/resources/templates/notifications/noticeWrite.html
Labels: Back

#52 45 헤더 콘텐츠 푸터 간의 간격 일관성 조정
  src/main/resources/static/css/fragments/footer.css
  src/main/resources/static/css/fragments/header.css
  src/main/resources/static/css/list/main.css
  src/main/resources/templates/error/404.html
  src/main/resources/templates/list/main.html
Labels: Front

#55 콘테스트 지원 페이지 연결
  src/main/java/com/DOH/DOH/controller/list/ContestListController.java
  src/main/resources/static/js/list/apply_1.js
Labels: documentation

#57 49 헤더 및 푸터 연결 및 네비게이션 설정
  src/main/resources/application.yml
  src/main/resources/static/css/contest/ContestPay2.css
  src/main/resources/static/css/contest/ContestUpload.css
  src/main/resources/static/css/contest/ContestUpload1.css
  src/main/resources/static/css/fragments/footer.css
  src/main/resources/static/css/fragments/header.css
  src/main/resources/static/css/list/applyInfDetail.css
  src/main/resources/static/css/list/apply_1.css
  src/main/resources/static/css/list/apply_2.css
  src/main/resources/static/css/list/contestList.css
  src/main/resources/static/css/list/main.css
  src/main/resources/static/css/notifications/eventList.css
  src/main/resources/static/css/notifications/noticeList.css
  src/main/resources/static/css/notifications/noticeWrite.css
  src/main/resources/static/css/user/MyPage.css
  src/main/resources/static/css/user/MyPageUpload.css
  src/main/resources/static/css/user/portfolioDetail.css
  src/main/resources/templates/fragments/List.html
  src/main/resources/templates/fragments/footer.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/fragments/layout.html
  src/main/resources/templates/list/applyInfDetail.html
  src/main/resources/templates/list/apply_1.html
  src/main/resources/templates/list/apply_2.html
  src/main/resources/templates/list/main.html
  src/main/resources/templates/notifications/eventList.html
  src/main/resources/templates/notifications/eventView.html
  src/main/resources/templates/notifications/eventWrite.html
  src/main/resources/templates/notifications/noticeList.html
  src/main/resources/templates/notifications/noticeWrite.html
  src/main/resources/templates/user/MyPage.html
  src/main/resources/templates/user/MyPagePortFolio.html
  src/main/resources/templates/user/MyPageProfile.html
  src/main/resources/templates/user/MyPageUpload.html
  src/main/resources/templates/user/portfolioDetail.html
Labels: Front

#59 AWS S3를 이용한 저장소 구축
  .gitignore
  build.gradle
  src/main/java/com/DOH/DOH/configuration/S3Config.java
  src/main/resources/application.yml
Labels: enhancement

#62 로그인, 회원가입 프론트 파일 업로드
  src/main/resources/static/css/user/login.css
  src/main/resources/static/css/user/register.css
  src/main/resources/static/img/fragments/googleLogo.png
  src/main/resources/static/img/fragments/kakaoLogo.png
  src/main/resources/static/img/fragments/logoGG.png
  src/main/resources/static/img/fragments/naverLogo.png
  src/main/resources/static/js/user/register.js
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/register.html
Labels: Front

#66 58 aws s3를 이용한 저장소 구축
  .gitignore
  src/main/java/com/DOH/DOH/configuration/S3Config.java
  src/main/java/com/DOH/DOH/controller/notifications/EventController.java
  src/main/resources/application.yml
  src/main/resources/static/css/notifications/eventList.css
  src/main/resources/templates/fragments/layout.html
  src/main/resources/templates/notifications/eventList.html
  src/main/resources/templates/notifications/eventWrite.html
  src/main/resources/templates/notifications/noticeList.html
Labels: enhancement

#68 51 결제api 기능 구현(테스트 버전)
  src/main/java/com/DOH/DOH/controller/contest/ContestUploadController.java
  src/main/resources/application.properties
  src/main/resources/static/css/contest/ContestPay2.css
  src/main/resources/static/js/contest/Pay.js
  src/main/resources/templates/contest/ContestPay2.html
  src/main/resources/templates/contest/ContestUpload1.html
  src/main/resources/templates/contest/ContestView.html
  src/main/resources/templates/contest/Pay.html
  src/main/resources/templates/contest/Pay1.html
Labels: Front, Back

#72 63 스프링시큐리티 적용
  build.gradle
  src/main/java/com/DOH/DOH/configuration/securityConfig.java
  src/main/java/com/DOH/DOH/controller/Test.java
  src/main/java/com/DOH/DOH/controller/list/MainController.java
  src/main/java/com/DOH/DOH/controller/user/LoginController.java
  src/main/java/com/DOH/DOH/controller/user/RegisterController.java
  src/main/java/com/DOH/DOH/dto/user/CustomUserDetails.java
  src/main/java/com/DOH/DOH/dto/user/LoginDTO.java
  src/main/java/com/DOH/DOH/dto/user/RegisterDTO.java
  src/main/java/com/DOH/DOH/mapper/user/LoginMapper.java
  src/main/java/com/DOH/DOH/mapper/user/RegisterMapper.java
  src/main/java/com/DOH/DOH/service/user/CustomUserDetailsService.java
  src/main/java/com/DOH/DOH/service/user/LoginService.java
  src/main/java/com/DOH/DOH/service/user/LoginServiceImpl.java
  src/main/java/com/DOH/DOH/service/user/RegisterService.java
  src/main/java/com/DOH/DOH/service/user/RegisterServiceImpl.java
  src/main/java/com/DOH/DOH/service/user/UserSessionService.java
  src/main/resources/mapper/user/LoginMapper.xml
  src/main/resources/mapper/user/RegisterMapper.xml
  src/main/resources/static/css/user/login.css
  src/main/resources/static/css/user/register.css
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/notifications/noticeList.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/register.html
Labels: Front, Back

#73 67 메인 페이지 슬라이드 기능 구현
  src/main/resources/static/css/list/main.css
  src/main/resources/static/img/banner/또우광고.png
  src/main/resources/static/img/banner/채팅.png
  src/main/resources/static/img/banner/콘테스트.png
  src/main/resources/static/img/banner/한가위.png
  src/main/resources/static/js/list/main.js
  src/main/resources/templates/list/main.html
  src/main/resources/templates/list/test.html
Labels: enhancement, Front

#78 74 헤더에 관리자 및 회원 권한 적용
  src/main/java/com/DOH/DOH/configuration/configure.java
  src/main/java/com/DOH/DOH/configuration/securityConfig.java
  src/main/java/com/DOH/DOH/controller/Test.java
  src/main/java/com/DOH/DOH/controller/common/CommonDataAdvice.java
  src/main/java/com/DOH/DOH/controller/list/MainController.java
  src/main/java/com/DOH/DOH/controller/notifications/NoticeController.java
  src/main/java/com/DOH/DOH/mapper/TestMapper.java
  src/main/java/com/DOH/DOH/service/TestService.java
  src/main/resources/mapper/TestMapper.xml
  src/main/resources/static/css/fragments/header.css
  src/main/resources/templates/error/404.html
  src/main/resources/templates/fragments/header.html
Labels: enhancement, Back

#82 81 헤더 알림기능 UI 적용
  src/main/resources/static/css/fragments/header.css
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/notifications/eventList.html
  src/main/resources/templates/notifications/eventView.html
  src/main/resources/templates/notifications/eventWrite.html
  src/main/resources/templates/notifications/noticeList.html
  src/main/resources/templates/notifications/noticeWrite.html
Labels: Front

#84 Revert "81 헤더 알림기능 UI 적용"
  src/main/resources/static/css/fragments/header.css
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/notifications/eventList.html
  src/main/resources/templates/notifications/eventView.html
  src/main/resources/templates/notifications/eventWrite.html
  src/main/resources/templates/notifications/noticeList.html
  src/main/resources/templates/notifications/noticeWrite.html
Labels: Front

#85 83 레이아웃 파일 내 링크 정리 및 통합 작업
  src/main/resources/static/css/chat/Chat.css
  src/main/resources/static/css/contest/ContestUpload.css
  src/main/resources/static/css/contest/ContestUpload1.css
  src/main/resources/static/css/fragments/quickMenu.css
  src/main/resources/static/css/list/main.css
  src/main/resources/static/js/chat/List.css
  src/main/resources/static/js/list/quickMenu.js
  src/main/resources/templates/chat/List.html
  src/main/resources/templates/contest/ContestPay2.html
  src/main/resources/templates/contest/ContestUpload.html
  src/main/resources/templates/contest/ContestUpload1.html
  src/main/resources/templates/contest/ContestView.html
  src/main/resources/templates/contest/Pay.html
  src/main/resources/templates/contest/Pay1.html
  src/main/resources/templates/fragments/footer.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/fragments/layout.html
  src/main/resources/templates/fragments/quickMenu.html
  src/main/resources/templates/list/applyInfDetail.html
  src/main/resources/templates/list/apply_1.html
  src/main/resources/templates/list/apply_2.html
  src/main/resources/templates/list/contestList.html
  src/main/resources/templates/list/main.html
  src/main/resources/templates/list/portfolioList.html
  src/main/resources/templates/list/test.html
  src/main/resources/templates/notifications/eventList.html
  src/main/resources/templates/notifications/eventView.html
  src/main/resources/templates/notifications/eventWrite.html
  src/main/resources/templates/notifications/noticeList.html
  src/main/resources/templates/notifications/noticeWrite.html
  src/main/resources/templates/user/MyPage.html
  src/main/resources/templates/user/MyPagePortFolio.html
  src/main/resources/templates/user/MyPageProfile.html
  src/main/resources/templates/user/MyPageUpload.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/portfolioDetail.html
  src/main/resources/templates/user/register.html
Labels: enhancement, Front

#87 채팅알림js추가
  src/main/resources/static/js/list/quickMenu.js
  src/main/resources/templates/fragments/footer.html
Labels: Front

#90 마이페이지 백엔드 기능 구현
  src/main/java/com/DOH/DOH/configuration/securityConfig.java
  src/main/java/com/DOH/DOH/controller/list/MainController.java
  src/main/java/com/DOH/DOH/controller/user/MyPageController.java
  src/main/java/com/DOH/DOH/dto/user/CustomUserDetails.java
  src/main/java/com/DOH/DOH/dto/user/MyPageDTO.java
  src/main/java/com/DOH/DOH/dto/user/MyPageProfileDTO.java
  src/main/java/com/DOH/DOH/dto/user/MyPageSkillDTO.java
  src/main/java/com/DOH/DOH/dto/user/PortFolioUploadDTO.java
  src/main/java/com/DOH/DOH/mapper/user/MyPageMapper.java
  src/main/java/com/DOH/DOH/mapper/user/MyPageProfileMapper.java
  src/main/java/com/DOH/DOH/mapper/user/PortFolioUploadMapper.java
  src/main/java/com/DOH/DOH/service/user/CustomUserDetailsService.java
  src/main/java/com/DOH/DOH/service/user/MyPageProfileService.java
  src/main/java/com/DOH/DOH/service/user/MyPageProfileServiceImpl.java
  src/main/java/com/DOH/DOH/service/user/MyPageService.java
  src/main/java/com/DOH/DOH/service/user/MyPageServiceImpl.java
  src/main/java/com/DOH/DOH/service/user/PortFolioUploadService.java
  src/main/java/com/DOH/DOH/service/user/PortFolioUploadServiceImpl.java
  src/main/java/com/DOH/DOH/service/user/UserSessionService.java
  src/main/resources/application.yml
  src/main/resources/mapper/user/MyPageMapper.xml
  src/main/resources/mapper/user/MyPageProfileMapper.xml
  src/main/resources/mapper/user/PortFolioUploadMapper.xml
  src/main/resources/static/css/user/MyPage.css
  src/main/resources/static/css/user/MyPagePortFolio.css
  src/main/resources/static/css/user/MyPageUpload.css
  src/main/resources/static/js/user/MyPageUpload.js
  src/main/resources/templates/user/MyPage.html
  src/main/resources/templates/user/MyPagePortFolio.html
  src/main/resources/templates/user/MyPageProfile.html
  src/main/resources/templates/user/MyPageUpload.html
  src/main/resources/templates/user/login.html
Labels: Front, Back

#89 닉네임 필드 추가 및 공통 데이터 로직 개선
  src/main/java/com/DOH/DOH/configuration/securityConfig.java
  src/main/java/com/DOH/DOH/controller/common/CommonDataAdvice.java
  src/main/java/com/DOH/DOH/controller/list/MainController.java
  src/main/java/com/DOH/DOH/controller/user/RegisterController.java
  src/main/java/com/DOH/DOH/dto/user/CustomUserDetails.java
  src/main/java/com/DOH/DOH/dto/user/RegisterDTO.java
  src/main/java/com/DOH/DOH/service/user/UserSessionService.java
  src/main/resources/mapper/user/RegisterMapper.xml
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/user/register.html
Labels: Front, Back

#99 채팅방 기능 구현
  build.gradle
  src/main/java/com/DOH/DOH/configuration/chat/WebSocketConfig.java
  src/main/java/com/DOH/DOH/controller/chat/ChatApiController.java
  src/main/java/com/DOH/DOH/controller/chat/ChatController.java
  src/main/java/com/DOH/DOH/controller/chat/ChatPageController.java
  src/main/java/com/DOH/DOH/controller/list/ProfileListController.java
  src/main/java/com/DOH/DOH/dto/chat/ChatDTO.java
  src/main/java/com/DOH/DOH/dto/chat/MessageDTO.java
  src/main/java/com/DOH/DOH/mapper/chat/ChatMapper.java
  src/main/java/com/DOH/DOH/service/chat/ChatService.java
  src/main/java/com/DOH/DOH/service/chat/ChatServiceImpl.java
  src/main/resources/mapper/chat/ChatMapper.xml
  src/main/resources/static/css/chat/chatRoom.css
  src/main/resources/static/js/chat/chatRoom.js
  src/main/resources/static/js/list/quickMenu.js
  src/main/resources/templates/chat/chatRoom.html
  src/main/resources/templates/fragments/footer.html
  src/main/resources/templates/user/portfolioDetail.html
Labels: enhancement

#107 77 공지사항 백엔드2차 씨큐리티 적용 임시저장 등록 확인하기
  src/main/java/com/DOH/DOH/controller/notifications/NoticeController.java
  src/main/java/com/DOH/DOH/dto/notifications/NoticeDTO.java
  src/main/java/com/DOH/DOH/dto/user/CustomUserDetails.java
  src/main/java/com/DOH/DOH/mapper/notifications/NoticeMapper.java
  src/main/java/com/DOH/DOH/service/notifications/NoticeService.java
  src/main/java/com/DOH/DOH/service/notifications/NoticeServiceImpl.java
  src/main/java/com/DOH/DOH/service/user/UserSessionService.java
  src/main/resources/mapper/notifications/NoticeMapper.xml
  src/main/resources/static/css/fragments/header.css
  src/main/resources/static/css/notifications/noticeList.css
  src/main/resources/static/css/notifications/noticeWrite.css
  src/main/resources/static/js/notifications/noticeList.js
  src/main/resources/static/js/notifications/noticeWrite.js
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/notifications/noticeList.html
  src/main/resources/templates/notifications/noticeWrite.html
Labels: Back

#106 103 알림 드롭다운 기능 추가
  src/main/resources/static/css/fragments/header.css
  src/main/resources/static/js/user/header.js
  src/main/resources/templates/fragments/header.html
Labels: Front

#112 71 결제 api 기능 구현프로젝트 적용
  src/main/java/com/DOH/DOH/controller/contest/ContestUploadController.java
  src/main/java/com/DOH/DOH/dto/contest/ContestUploadDTO.java
  src/main/java/com/DOH/DOH/mapper/contest/ContestUploadMapper.java
  src/main/java/com/DOH/DOH/service/contest/ContestUploadService.java
  src/main/java/com/DOH/DOH/service/contest/ContestUploadServiceImpl.java
  src/main/resources/mapper/contest/ContestUploadMapper.xml
  src/main/resources/static/js/contest/Pay.js
  src/main/resources/templates/contest/ContestPay2.html
  src/main/resources/templates/contest/ContestUpload.html
  src/main/resources/templates/contest/ContestUpload1.html
  src/main/resources/templates/contest/Pay.html
  src/main/resources/templates/contest/Pay1.html
  src/main/resources/templates/fragments/header.html
Labels: Front, Back

#111 컨테스트 등록 페이지 백엔드 수정 및 S3 이미지 업로드 기능 구현
  src/main/java/com/DOH/DOH/controller/list/ApplyController.java
  src/main/java/com/DOH/DOH/dto/list/ApplyDTO.java
  src/main/java/com/DOH/DOH/mapper/list/ContestListMapper.java
  src/main/java/com/DOH/DOH/service/common/S3FileUploadService.java
  src/main/java/com/DOH/DOH/service/list/ContestListService.java
  src/main/java/com/DOH/DOH/service/list/ContestListServiceImpl.java
  src/main/resources/mapper/list/ContestListMapper.xml
  src/main/resources/static/js/list/applicationTerms.js
  src/main/resources/static/js/list/applicationWrite.js
  src/main/resources/templates/list/applicationWrite.html
Labels: enhancement, Back

#114 :bug: 컨테스트 서비스 오류 수정
  src/main/java/com/DOH/DOH/controller/list/ApplyController.java
  src/main/java/com/DOH/DOH/service/list/ContestListService.java
  src/main/java/com/DOH/DOH/service/list/ContestListServiceImpl.java
Labels: bug

#115 113 콘테스트 이미지 업로드 구현
  src/main/java/com/DOH/DOH/controller/contest/ContestUploadController.java
  src/main/java/com/DOH/DOH/dto/contest/ContestUploadDTO.java
  src/main/resources/static/js/contest/ContestUpload.js
  src/main/resources/templates/contest/ContestUpload.html
  src/main/resources/templates/contest/ContestView.html
Labels: Front, Back

#119 컨테스트 결과창 프론트단 구현
  src/main/java/com/DOH/DOH/controller/contest/ContestResultController.java
  src/main/resources/static/img/contest/trophy1.jpeg
  src/main/resources/static/img/contest/trophy2.jpeg
  src/main/resources/static/img/contest/trophy3.jpeg
  src/main/resources/templates/contest/result.html
Labels: Front

#128 121 결제 취소 시 컨테스트 등록 자동 취소 기능 구현
  src/main/java/com/DOH/DOH/controller/contest/ContestUploadController.java
  src/main/java/com/DOH/DOH/dto/contest/ContestUploadDTO.java
  src/main/resources/mapper/contest/ContestUploadMapper.xml
  src/main/resources/templates/contest/ContestPay2.html
  src/main/resources/templates/contest/ContestView.html
Labels: bug, Back

#127 95 이메일 인증 및 회원가입 폼 구현
  build.gradle
  src/main/java/com/DOH/DOH/configuration/EmailConfig.java
  src/main/java/com/DOH/DOH/controller/user/EmailController.java
  src/main/java/com/DOH/DOH/dto/user/EmailDTO.java
  src/main/java/com/DOH/DOH/service/user/EmailService.java
  src/main/resources/static/css/user/login.css
  src/main/resources/static/css/user/register.css
  src/main/resources/static/js/user/register.js
  src/main/resources/templates/user/email-template.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/register.html
Labels: Front, Back

#129 메인페이지 정보 출력
  src/main/java/com/DOH/DOH/controller/list/MainController.java
  src/main/java/com/DOH/DOH/dto/list/ContestListDTO.java
  src/main/java/com/DOH/DOH/mapper/list/MainMapper.java
  src/main/java/com/DOH/DOH/service/list/MainService.java
  src/main/java/com/DOH/DOH/service/list/MainServiceImpl.java
  src/main/resources/mapper/list/MainMapper.xml
  src/main/resources/static/css/list/main.css
  src/main/resources/static/img/default_image.png
  src/main/resources/static/js/list/main.js
  src/main/resources/templates/list/main.html
Labels: enhancement, Front, Back

#134 108 이벤트 백엔드2차 씨큐리티 적용 임시저장 등록이미지저장등록 확인하기
  src/main/java/com/DOH/DOH/controller/notifications/DateUtils.java
  src/main/java/com/DOH/DOH/controller/notifications/EventController.java
  src/main/java/com/DOH/DOH/dto/notifications/EventDTO.java
  src/main/java/com/DOH/DOH/mapper/notifications/EventMapper.java
  src/main/java/com/DOH/DOH/service/common/S3FileUploadService.java
  src/main/java/com/DOH/DOH/service/notifications/EventService.java
  src/main/java/com/DOH/DOH/service/notifications/EventServiceImpl.java
  src/main/resources/mapper/notifications/EventMapper.xml
  src/main/resources/static/css/notifications/eventList.css
  src/main/resources/static/img/fragments/noimg.png
  src/main/resources/static/js/list/quickMenu.js
  src/main/resources/static/js/notifications/eventList.js
  src/main/resources/static/js/notifications/eventView.js
  src/main/resources/static/js/notifications/eventWrite.js
  src/main/resources/templates/notifications/eventList.html
  src/main/resources/templates/notifications/eventView.html
  src/main/resources/templates/notifications/eventWrite.html
Labels: enhancement, Front, Back

#138 :bug: 오류 수정
  src/main/java/com/DOH/DOH/dto/contest/ContestUploadDTO.java
  src/main/java/com/DOH/DOH/service/list/ContestListServiceImpl.java
Labels: bug

#144 프론트엔드 디자인 개선
  src/main/resources/static/css/contest/contestAward.css
  src/main/resources/static/css/contest/result.css
  src/main/resources/static/css/user/MyPage.css
  src/main/resources/static/img/contest/trophy1.jpeg
  src/main/resources/static/img/contest/trophy2.jpeg
  src/main/resources/static/img/contest/trophy3.jpeg
  src/main/resources/templates/contest/contestAward.html
  src/main/resources/templates/contest/result.html
  src/main/resources/templates/user/MyPage.html
Labels: enhancement, Front

#147 139 지원 상세 페이지 수정 및 페이지 연결 및 css 수정
  src/main/java/com/DOH/DOH/controller/list/ApplyController.java
  src/main/java/com/DOH/DOH/mapper/list/ContestListMapper.java
  src/main/java/com/DOH/DOH/service/list/ContestListService.java
  src/main/java/com/DOH/DOH/service/list/ContestListServiceImpl.java
  src/main/resources/mapper/list/ContestListMapper.xml
  src/main/resources/static/css/list/applyInfDetail.css
  src/main/resources/static/js/list/applyInfDetail.js
  src/main/resources/templates/contest/ContestView.html
  src/main/resources/templates/list/applyInfDetail.html
Labels: Front, Back

#149 130 닉네임 및 이메일 중복 확인 기능 구현
  src/main/java/com/DOH/DOH/configuration/securityConfig.java
  src/main/java/com/DOH/DOH/controller/user/RegisterController.java
  src/main/java/com/DOH/DOH/mapper/user/RegisterMapper.java
  src/main/java/com/DOH/DOH/service/user/RegisterService.java
  src/main/java/com/DOH/DOH/service/user/RegisterServiceImpl.java
  src/main/resources/mapper/user/RegisterMapper.xml
  src/main/resources/static/js/user/login.js
  src/main/resources/static/js/user/register.js
  src/main/resources/templates/user/login.html
Labels: Back

#150 마이페이지 프로필 사진 업로드 적용 기능 구현
  src/main/java/com/DOH/DOH/controller/user/MyPageController.java
  src/main/java/com/DOH/DOH/dto/user/MyPageDTO.java
  src/main/java/com/DOH/DOH/mapper/user/MyPageMapper.java
  src/main/java/com/DOH/DOH/service/user/MyPageService.java
  src/main/java/com/DOH/DOH/service/user/MyPageServiceImpl.java
  src/main/resources/mapper/user/MyPageMapper.xml
  src/main/resources/static/css/user/MyPage.css
  src/main/resources/templates/user/MyPage.html
Labels: Front, Back

#155 마이페이지 이미지 버그 해결
  src/main/resources/templates/user/MyPage.html
Labels: bug, Back

#157 137 전체 프론트 디자인 마무리 작업
  src/main/java/com/DOH/DOH/controller/notifications/EventController.java
  src/main/java/com/DOH/DOH/controller/notifications/NoticeController.java
  src/main/java/com/DOH/DOH/service/notifications/EventServiceImpl.java
  src/main/java/com/DOH/DOH/service/notifications/NoticeService.java
  src/main/java/com/DOH/DOH/service/notifications/NoticeServiceImpl.java
  src/main/resources/mapper/notifications/EventMapper.xml
  src/main/resources/static/css/chat/chatRoom.css
  src/main/resources/static/css/contest/ContestView.css
  src/main/resources/static/css/contest/contestAward.css
  src/main/resources/static/css/fragments/header.css
  src/main/resources/static/css/fragments/quickMenu.css
  src/main/resources/static/css/list/applicationWrite.css
  src/main/resources/static/css/list/contestList.css
  src/main/resources/static/css/list/portfolioList.css
  src/main/resources/static/css/notifications/eventList.css
  src/main/resources/static/css/notifications/eventView.css
  src/main/resources/static/css/notifications/eventWrite.css
  src/main/resources/static/css/notifications/noticeList.css
  src/main/resources/static/css/notifications/noticeWrite.css
  src/main/resources/static/css/user/MyPage.css
  src/main/resources/static/css/user/portfolioDetail.css
  src/main/resources/static/img/chaatimg.png
  src/main/resources/static/js/notifications/noticeList.js
  src/main/resources/static/js/user/MyPageUpload.js
  src/main/resources/templates/chat/chatRoom.html
  src/main/resources/templates/contest/ContestView.html
  src/main/resources/templates/contest/contestAward.html
  src/main/resources/templates/fragments/footer.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/list/applicationTerms.html
  src/main/resources/templates/list/applicationWrite.html
  src/main/resources/templates/list/applyInfDetail.html
  src/main/resources/templates/list/contestList.html
  src/main/resources/templates/list/contestWrap_ajax.html
  src/main/resources/templates/list/portfolioList.html
  src/main/resources/templates/notifications/eventList.html
  src/main/resources/templates/notifications/eventView.html
  src/main/resources/templates/notifications/eventWrite.html
  src/main/resources/templates/notifications/noticeList.html
  src/main/resources/templates/user/MyPage.html
  src/main/resources/templates/user/MyPageUpload.html
Labels: enhancement, Front

#159 - 주문번호로 인한 결제 버그 수정
  src/main/java/com/DOH/DOH/service/contest/ContestUploadServiceImpl.java
Labels: bug

#160 101 채팅방 버그개선
  src/main/java/com/DOH/DOH/controller/chat/ChatApiController.java
  src/main/java/com/DOH/DOH/controller/chat/ChatPageController.java
  src/main/java/com/DOH/DOH/controller/user/MyPageController.java
  src/main/java/com/DOH/DOH/dto/chat/MessageDTO.java
  src/main/java/com/DOH/DOH/dto/user/MyPageDTO.java
  src/main/java/com/DOH/DOH/mapper/chat/ChatMapper.java
  src/main/java/com/DOH/DOH/mapper/user/MyPageMapper.java
  src/main/java/com/DOH/DOH/service/chat/ChatService.java
  src/main/java/com/DOH/DOH/service/user/MyPageService.java
  src/main/java/com/DOH/DOH/service/user/MyPageServiceImpl.java
  src/main/resources/mapper/chat/ChatMapper.xml
  src/main/resources/mapper/user/MyPageMapper.xml
  src/main/resources/static/css/fragments/quickMenu.css
  src/main/resources/static/js/list/quickMenu.js
  src/main/resources/templates/chat/chatRoom.html
Labels: bug
